### ISSUE TITLE
npx gomplate "could not determine executable to run"

### ISSUE THREAD

**Issue by devthejo** [gomplate/gomplate-npm#8]
the bin is not at the good path in npm package:
here is my current workaround, I had to link it manually
```json
{
  "scripts": {
    "postinstall": "ln -s ../gomplate/node_modules/.bin/gomplate node_modules/.bin/gomplate"
  }
}

**Comment by hairyhenderson** [comment]
Thanks for moving this over, @devthejo!

@RecuencoJones do you think you could have a look at this?

**Comment by RecuencoJones** [comment]
Can you please share some details about the environment?

- node version
- npm version
- gomplate version

**Comment by RecuencoJones** [comment]
I think I found the issue 😄 
Was trying to reproduce with latest from my go-npm fork, but it is already fixed there!

https://github.com/RecuencoJones/go-npm/blob/master/src/common.js#L45

**Comment by devthejo** [comment]
Thanks for fixing it, I wait impatiently for the npm release, for now
```js
docker run --rm node:16-alpine npx gomplate --version
```
> npm ERR! could not determine executable to run

**Comment by hairyhenderson** [comment]
I think we could publish a new version, but then the version wouldn't line up with gomplate's version... 🤔

I'd also like to get a new gomplate release out soon (it's been waaaay too long), so once that happens the npm package will be up-to-date as well... Also note that there are a number of other ways to [install gomplate](https://docs.gomplate.ca/installing/) 😉

**Comment by RecuencoJones** [comment]
Using GitHub dependencies on the package.json should be also possible:

```
  "gomplate": "gomplate/gomplate-npm"
```
